services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: respirebem
      POSTGRES_USER: respirebem
      POSTGRES_PASSWORD: respirebem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U respirebem"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongodb:
    image: mongo:7.0.12
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  mongodb_data:
